# Generated by Django 4.2.7 on 2025-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cabinet', '0004_alter_secretaire_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('google_maps_url', models.URLField(help_text="URL de l'iframe Google Maps")),
                ('description', models.TextField()),
                ('horaires', models.TextField(help_text="Horaires d'ouverture du cabinet")),
            ],
            options={
                'verbose_name': 'Information du cabinet',
                'verbose_name_plural': 'Informations du cabinet',
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='staff_photos/')),
                ('ordre_affichage', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='SpecialiteCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='specialites_images/')),
                ('ordre_affichage', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['ordre_affichage'],
            },
        ),
    ]
